### ISSUE TITLE
SAC: Implement writing of headers only

### ISSUE THREAD

**Issue by LFRPuente** [anowacki/Seis.jl#11]

**Comment by anowacki** [comment]
Per an email exchange, this is a feature request to implement writing of only headers over existing SAC files.

**Comment by anowacki** [comment]
Notes:
- Easy enough to do.
- Optimally will be part of rearrangement of all IO such that routines can accept an `IO` object rather than only a file name.
- This would enable overwriting only the header portion of a SAC file which has been `open()`ed.

**Comment by anowacki** [comment]
Closed by #25.
