### ISSUE TITLE
Unresolved dependencies, can't install

### ISSUE THREAD

**Issue by jpjones76** [anowacki/Seis.jl#4]
I can't install this package using the current instructions in Readme.md:
> (v1.0) pkg> add https://github.com/anowacki/Geodesics.jl https://github.com/anowacki/TauPy.jl https://github.com/anowacki/Seis.jl
>   Updating registry at `~/.julia/registries/General`
>   Updating git-repo `https://github.com/JuliaRegistries/General.git`
>   Updating git-repo `https://github.com/anowacki/Geodesics.jl`
>   Updating git-repo `https://github.com/anowacki/TauPy.jl`
>   Updating git-repo `https://github.com/anowacki/Seis.jl`
>  Resolving package versions...
> ERROR: Unsatisfiable requirements detected for package SAC [03de775e]:
>  SAC [03de775e] log:
>  ├─SAC [03de775e] has no known versions!
>  └─restricted to versions * by Seis [dd80f4d8] — no versions left
>    └─Seis [dd80f4d8] log:
>      ├─possible versions are: 0.1.1 or uninstalled
>      └─Seis [dd80f4d8] is fixed to version 0.1.1

I also can't install it by following the guidelines in #1 :
> (v1.0) pkg> add https://github.com/anowacki/Geodesics.jl https://github.com/anowacki/SAC.jl https://github.com/anowacki/TauPy.jl
>   Updating git-repo `https://github.com/anowacki/Geodesics.jl`
>   Updating git-repo `https://github.com/anowacki/SAC.jl`
>   Updating git-repo `https://github.com/anowacki/TauPy.jl`
>  Resolving package versions...
>   Updating `~/.julia/environments/v1.0/Project.toml`
>  [no changes]
>   Updating `~/.julia/environments/v1.0/Manifest.toml`
>  [no changes]
>   Building TauPy → `~/.julia/packages/TauPy/Wlsc9/deps/build.log`
> ┌ Error: Error building `TauPy`: 
> │ ERROR: LoadError: PyError (PyImport_ImportModule
> │ 
> │ The Python package geographiclib could not be found by pyimport. Usually this means
> │ that you did not install geographiclib in the Python version being used by PyCall.
> │ 
> │ PyCall is currently configured to use the Python version at:
> │ 
> │ python3
> │ 
> │ and you should use whatever mechanism you usually use (apt-get, pip, conda,
> │ etcetera) to install the Python package containing the geographiclib module.
> │ 
> │ One alternative is to re-configure PyCall to use a different Python
> │ version on your system: set ENV["PYTHON"] to the path/name of the python
> │ executable you want to use, run Pkg.build("PyCall"), and re-launch Julia.
> │ 
> │ Another alternative is to configure PyCall to use a Julia-specific Python
> │ distribution via the Conda.jl package (which installs a private Anaconda
> │ Python distribution), which has the advantage that packages can be installed
> │ and kept up-to-date via Julia.  As explained in the PyCall documentation,
> │ set ENV["PYTHON"]="", run Pkg.build("PyCall"), and re-launch Julia. Then,
> │ To install the geographiclib module, you can use `pyimport_conda("geographiclib", PKG)`,
> │ where PKG is the Anaconda package the contains the module geographiclib,
> │ or alternatively you can use the Conda package directly (via
> │ `using Conda` followed by `Conda.add` etcetera).
> │ 
> │ ) <class 'ModuleNotFoundError'>
> │ ModuleNotFoundError("No module named 'geographiclib'")
> │ 
> │ Stacktrace:
> │  [1] pyimport(::String) at /home/josh/.julia/packages/PyCall/0jMpb/src/PyCall.jl:486
> │  [2] pyimport_conda(::String, ::String, ::String) at /home/josh/.julia/packages/PyCall/0jMpb/src/PyCall.jl:650
> │  [3] top-level scope at none:0
> │  [4] include(::String) at ./client.jl:392
> │  [5] top-level scope at none:0
> │ in expression starting at /home/josh/.julia/packages/TauPy/Wlsc9/deps/build.jl:2
> └ @ Pkg.Operations /build/julia/src/julia-1.0.3/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
>
> shell> which python3
> /usr/bin/python3

It looks like the issue with TauPy is an unresolved dependency in another language (Python), which isn't in the installation instructions. 

Installing Seis.jl succeeds without TauPy, provided I have SAC.jl:
`(v1.0) pkg> add https://github.com/anowacki/Geodesics.jl https://github.com/anowacki/SAC.jl https://github.com/anowacki/Seis.jl`

However, when I try to use it:

> julia> import Seis
> [ Info: Precompiling Seis [dd80f4d8-c2f6-58bd-9bd3-4635f134261d]
> ERROR: LoadError: InitError: PyError (PyImport_ImportModule
> 
> The Python package geographiclib could not be found by pyimport. Usually this means
> that you did not install geographiclib in the Python version being used by PyCall.
> 
> PyCall is currently configured to use the Python version at:
> 
> python3
> 
> and you should use whatever mechanism you usually use (apt-get, pip, conda,
> etcetera) to install the Python package containing the geographiclib module.
> 
> One alternative is to re-configure PyCall to use a different Python
> version on your system: set ENV["PYTHON"] to the path/name of the python
> executable you want to use, run Pkg.build("PyCall"), and re-launch Julia.
> 
> Another alternative is to configure PyCall to use a Julia-specific Python
> distribution via the Conda.jl package (which installs a private Anaconda
> Python distribution), which has the advantage that packages can be installed
> and kept up-to-date via Julia.  As explained in the PyCall documentation,
> set ENV["PYTHON"]="", run Pkg.build("PyCall"), and re-launch Julia. Then,
> To install the geographiclib module, you can use `pyimport_conda("geographiclib", PKG)`,
> where PKG is the Anaconda package the contains the module geographiclib,
> or alternatively you can use the Conda package directly (via
> `using Conda` followed by `Conda.add` etcetera).
> 
> ) <class 'ModuleNotFoundError'>
> ModuleNotFoundError("No module named 'geographiclib'")
> 
> Stacktrace:
>  [1] pyimport(::String) at /home/josh/.julia/packages/PyCall/0jMpb/src/PyCall.jl:486
>  [2] pyimport_conda(::String, ::String, ::String) at /home/josh/.julia/packages/PyCall/0jMpb/src/PyCall.jl:650
>  [3] __init__() at /home/josh/.julia/packages/TauPy/Wlsc9/src/TauPy.jl:46
>  [4] top-level scope at none:2
> during initialization of module TauPy
> in expression starting at /home/josh/.julia/packages/Seis/cvZtG/src/Seis.jl:109
> ERROR: Failed to precompile Seis [dd80f4d8-c2f6-58bd-9bd3-4635f134261d] to /home/josh/.julia/compiled/v1.0/Seis/nmNAD.ji.

If TauPy.jl is part of the core functionality needed for me to bugtest your SEED issue in jpjones76/SeisIO.jl/#7, then could you please include all Python library requirements and add their installation guidelines to Readme.md? Thanks!

**Comment by anowacki** [comment]
Thanks for this experience.  The current installation instructions are bad and the whole process is less than ideal.  I've added this to #2 to track.

Hopefully the [comment](https://github.com/jpjones76/SeisIO.jl/issues/7#issuecomment-463600255) in jpjones76/SeisIO.jl#7 is enough to get the test case working.

The reason it works for some but not others is that if you use Conda.jl's internal python, then it will install obspy for you.  When you're using your own python like you are here, then you will need to install it separately.

**Comment by anowacki** [comment]
By the way, does [this option](https://github.com/anowacki/Seis.jl#installation-issues-with-python) work for you?

**Comment by jpjones76** [comment]
Yes, that worked with minor modifications. I had to install Conda.jl and do `ENV["PYTHON"] = ""; import Pkg; Pkg.build("PyCall")`.Otherwise it couldn't handle installing the dependencies.

If I can make one suggestion, here, I think users will find installation easier if you make the Conda-based install the expectation, i.e., 
1. Add Conda and PyCall to TauPy's REQUIRE file
1. Modify the guide in Readme.md to require that users run `ENV["PYTHON"] = ""; import Pkg; Pkg.build("PyCall")` before installing. Two reasons:
   + If you leave this as a mere suggestion, you're guaranteed to get some first-year student opening issues because their absurd python customization breaks everything. 
   + Python installations like to do non-standard things that break ObsPy installations. Most Linux distributions make some modification; I think Ubuntu doesn't. Windows is worse; only Spyder runs ObsPy for me; other Python versions won't even install SciPy.

**Comment by anowacki** [comment]
Great, thanks very much for trying that and those suggestions.  I'm tracking this at anowacki/TauPy.jl#3.

The call to `Pycall.pyimport_conda` in [`TauPy.__init__()`](https://github.com/anowacki/TauPy.jl/blob/cd80fc50c97192c376b2e0c537892d03d59542ea/src/TauPy.jl#L44) is supposed to install Conda and Obspy for you so long as you have installed/built PyCall without `$PYTHON` set, but there are [problems](https://travis-ci.org/anowacki/TauPy.jl).  I would love to drop the TauPy (and Obspy, hence Python) requirement and have global seismic travel times and ray paths in pure Julia, but that's a significant effort.
